services:
  - type: web
    name: letsbunk-server
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    runtime: node
    nodeVersion: 18.20.4
    autoDeploy: true
    branch: master